/* Generated by scripts/create_radio.py: radio page text, one ROM bank. */
#pragma bank 255
#include <gbdk/platform.h>
static const UBYTE td_rs2[24]={7,0,8,8,7,7,14,14,0,14,14,0,0,0,0,0,0,0,0,0,0,0,0,0};
/* Exactly 38 characters each: no terminating NUL is stored. */
static const char td_rt2[24][38]={
    "FOR THE DINO HALL. RECEIVING DESK.    ",
    "IT'S A BONE.       BE GENTLE.         ",
    "WEN: THE DOCTOR'S  CAST. BUBBLE WRAP, ",
    "THREE LAYERS.                         ",
    "DR HALE: IT FITS.  THE                ",
    "HALL IS COMPLETE.                     ",
    "LEE: KIOSK STOCK ATUNION'S GREAT HALL.",
    "BRING IT TO EATON.                    ",
    "TWO DESKS,         BOTH INDOORS.      ",
    "LEE: PHONE CASES.  HUNDREDS OF THEM.  ",
    "LEE: SHELVES FULL. SALE AT NOON.      ",
    "STEAMER BASKETS    FROM KENSINGTON TO ",
    "DRAGON CITY.                          ",
    "HOT AND FAST.      DIM SUM WAITS FOR  ",
    "NO ONE.                               ",
    "STACKED SIX        HIGH. EASY NOW.    ",
    "THE STALL SAYS     THANKS. THEY SAVED ",
    "YOU A BUN.                            ",
    "LAUNCH DAY AT      BYTE BARN. ONE BOX ",
    "TO DUFFERIN.                          ",
    "THE LINE GOES      ROUND THE LOT. GO  ",
    "IN BY THE DESK.                       ",
    "SEALED. DON'T      SHAKE IT.          ",
    "DELIVERED BEFORE   THE LINE WAS DONE. ",
};
void td_radio_text2(UWORD page,UBYTE from,UBYTE n,char *dest) BANKED {
    const char *s=td_rt2[page-800]+from;while(n--)*dest++=*s++;
}
UBYTE td_radio_speaker2(UWORD page) BANKED {return td_rs2[page-800];}
