"""Generate the animated scenery tiles from the shared art in city_kit.

Two groups of background tiles change as the city runs:
  water   open water, the 32 x 32 px texture every scene shares (16 tiles):
          drifting ripples and twinkling glints;
  screen  the video screen on the roof at Yonge and Dundas (8 tiles).
Each has four frames. The engine (td_scenery.c) finds the first frame's
tiles in the scene's tilesets and swaps in the next frame a few times a
second.

Writes engine/include/td_scenery_data.h. `--check` verifies it without writing.
"""
import sys
from pathlib import Path
import city_kit as K

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'project/plugins/toronto-driving/engine/include/td_scenery_data.h'
GROUPS = (('WATER', K.water_tiles), ('SCREEN', K.screen_tiles))
FRAMES = 4


def tile_bytes(pixels):
    """64 COLORS indices -> 16 bytes; GB colour index is 3 - COLORS index
    (the lightest source shade is palette colour 0)."""
    out = []
    for y in range(8):
        lo = hi = 0
        for x in range(8):
            v = 3 - pixels[y * 8 + x]
            lo |= (v & 1) << (7 - x)
            hi |= (v >> 1) << (7 - x)
        out += [lo, hi]
    return out


def flips(p):
    h = [p[y * 8 + 7 - x] for y in range(8) for x in range(8)]
    v = [p[(7 - y) * 8 + x] for y in range(8) for x in range(8)]
    hv = [p[(7 - y) * 8 + 7 - x] for y in range(8) for x in range(8)]
    return [p, h, v, hv]


def build():
    frames = [[] for _ in range(FRAMES)]
    firsts, defines = [], []
    for name, make in GROUPS:
        tiles = make()
        assert len(tiles) == FRAMES
        defines.append(f'#define TD_SCENERY_{name} {len(frames[0])}')
        defines.append(f'#define TD_SCENERY_{name}_TILES {len(tiles[0])}')
        for f in range(FRAMES):
            frames[f] += tiles[f]
    first = frames[0]
    # GB Studio stores a tile once with its flips: every first-frame tile must
    # be distinct under flips, and none may be plain (a single colour), which
    # ordinary scenery could share.
    for i, a in enumerate(first):
        assert len(set(a)) > 1, f'scenery tile {i} is plain'
        for j, b in enumerate(first):
            assert i == j or all(b != f for f in flips(a)), f'scenery tiles {i} and {j} are flips'
    assert len(first) <= 32, 'the found mask is 32 bits'
    rows = ['  {' + ','.join('{' + ','.join(f'0x{b:02X}' for b in tile_bytes(t)) + '}' for t in tiles) + '}'
            for tiles in frames]
    text = '\n'.join([
        '/* Generated by scripts/create_scenery.py from the shared scenery art',
        ' * (scripts/city_kit.py). Original art. */',
        '#ifndef TD_SCENERY_DATA_H', '#define TD_SCENERY_DATA_H',
        f'#define TD_SCENERY_TILES {len(first)}', f'#define TD_SCENERY_FRAMES {FRAMES}', *defines,
        '#ifdef TD_SCENERY_DATA',
        '/* [frame][tile][2bpp bytes]: open water (tile = (y / 8 % 4) * 4 + x / 8 % 4',
        ' * on the scene), then the Yonge and Dundas screen (row-major). */',
        f'static const UBYTE td_scenery_frames[{FRAMES}][{len(first)}][16]={{',
        ',\n'.join(rows), '};', '#endif', '#endif', ''])
    return text, len(first)


def main():
    text, tiles = build()
    if '--check' in sys.argv:
        assert OUT.read_text() == text, 'scenery tiles are stale; run scripts/create_scenery.py'
        print(f'Animated scenery matches its art: {tiles} tiles, {FRAMES} frames.')
        return
    OUT.write_text(text)
    print(f'Wrote {OUT.relative_to(ROOT)}: {tiles} tiles, {FRAMES} frames.')


if __name__ == '__main__':
    main()
