"""Generate exact ROM interpolation from the existing authored Queen paths.

The native route geometry remains in td_streetcar.c. Tables replace only its
floor(length * tick / 720) arithmetic for the proven private tick range0..720.
Near pointers and values share that banked compilation unit; no WRAM is used.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "project/plugins/toronto-driving/engine"
SOURCE = ENGINE / "src/td_streetcar.c"
BEGIN = "/* BEGIN GENERATED STREETCAR PROGRESS */"
END = "/* END GENERATED STREETCAR PROGRESS */"


def initializer(source, name):
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", source, flags=re.S)
    match = re.search(r"\b" + re.escape(name) + r"(?:\s*\[[^]]*\])+\s*=\s*\{", source)
    assert match, f"Missing authored initializer: {name}"
    depth = 1
    for index in range(match.end(), len(source)):
        depth += (source[index] == "{") - (source[index] == "}")
        if not depth:
            return source[match.end():index]
    raise AssertionError(f"Unclosed authored initializer: {name}")


def model(source=None, district_header=None):
    source = SOURCE.read_text() if source is None else source
    district_header = (ENGINE / "include/td_district.h").read_text() if district_header is None else district_header
    districts = {name: int(value) for name, value in re.findall(
        r"^#define (TD_DISTRICT_[A-Z_]+) ([0-9]+)$", district_header, flags=re.M)}
    paths = initializer(source, "td_streetcar_paths")
    counts = [int(value.strip()) for value in initializer(source, "td_streetcar_path_counts").split(",")]
    rows = re.findall(r"\{((?:\s*\{[^{}]*\}\s*,?)+)\s*\}", paths)
    assert len(rows) == len(counts) == 16, "Review changes to the sixteen authored Queen sections"
    lengths = []
    for row, count in zip(rows, counts):
        points = []
        for point in re.findall(r"\{([^{}]*)\}", row):
            tokens = [value.strip() for value in point.split(",")]
            assert len(tokens) == 3 and tokens[2] in districts, "Unknown native route point"
            u, v = int(tokens[0]), int(tokens[1])
            assert 0 <= u <= 1024 and 0 <= v <= 976, "Authored route exceeds the native local scene"
            points.append((u, v, districts[tokens[2]]))
        assert len(points) == count and 2 <= count <= 4, "Authored path counts and points differ"
        length = 0
        for a, b in zip(points, points[1:]):
            if a[2] != b[2]:
                continue
            assert (a[0] == b[0]) != (a[1] == b[1]), "Queen travel edges must remain cardinal"
            length += (abs(a[0] - b[0]) + abs(a[1] - b[1])) * 16
        assert 0 < length <= 65535, "Native route length must fit UWORD"
        lengths.append(length)
    return lengths


def generated(source=None, district_header=None):
    lengths = model(source, district_header)
    lines = [BEGIN,
             "/* Generated by scripts/create_streetcar_progress.py from the paths/counts",
             " * above. Exact floor(length*tick/720), including both endpoints. All",
             " * values and near pointers live in this same bank; no persistent WRAM. */"]
    for length in sorted(set(lengths)):
        values = [length * tick // 720 for tick in range(721)]
        lines.append(f"static const UWORD td_streetcar_progress_{length}[721]={{")
        for start in range(0, len(values), 12):
            lines.append("    " + ",".join(map(str, values[start:start + 12])) + ",")
        lines.append("};")
    lines.append("static const UWORD * const td_streetcar_progress_routes[16]={")
    for start in range(0, len(lengths), 4):
        lines.append("    " + ",".join(f"td_streetcar_progress_{length}" for length in lengths[start:start + 4]) + ",")
    lines.extend(["};",
                  "typedef char td_streetcar_progress_routes_match_paths[",
                  "    (sizeof(td_streetcar_progress_routes)/sizeof(td_streetcar_progress_routes[0])==",
                  "     sizeof(td_streetcar_path_counts))?1:-1];",
                  "#ifdef __SDCC",
                  "typedef char td_streetcar_progress_near_pointer_fits[",
                  "    (sizeof(td_streetcar_progress_routes[0])==2)?1:-1];",
                  "#endif", END])
    return "\n".join(lines)


def main():
    source = SOURCE.read_text()
    assert source.count(BEGIN) == source.count(END) == 1, "Missing or duplicate generated block markers"
    pattern = re.escape(BEGIN) + r".*?" + re.escape(END)
    updated = re.sub(pattern, lambda _: generated(source), source, flags=re.S)
    if "--check" in sys.argv:
        assert updated == source, "Native streetcar progress tables are stale"
    else:
        SOURCE.write_text(updated)
    lengths = model(source)
    table_bytes = len(set(lengths)) * 721 * 2 + len(lengths) * 2
    print(f"Streetcar progress: {len(lengths)} routes, {len(set(lengths))} exact tables, "
          f"{table_bytes} native ROM data bytes, zero persistent WRAM")


if __name__ == "__main__":
    main()
