"""Generate the UI font, menu/HUD art tiles and glyph tables from ui_art.py.

Writes:
  engine/include/td_font.h     original bold UI font (CGB bank 1, tiles 192..)
  engine/include/td_ui_art.h   art tiles (bank 0, tiles 128..), glyph tile and
                                attribute tables for character codes 32..255,
                                code macros and the UI / map palettes
  project/project/palettes/default_ui.gbsres  UI palette (BG slot 7)
`--check` verifies the outputs without writing.
"""
import json
import sys
from pathlib import Path
import ui_art as A

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / 'project/plugins/toronto-driving/engine'
ART_FIRST, FONT_FIRST, FIRST_CODE, TITLE_FIRST = 128, 192, 0x80, 8
SHADE = {'.': 0, 'a': 1, 's': 2, '#': 3}


def tile_bytes(rows):
    out = []
    for row in rows:
        lo = hi = 0
        for x, ch in enumerate(row):
            v = SHADE[ch]
            lo |= (v & 1) << (7 - x)
            hi |= (v >> 1) << (7 - x)
        out += [lo, hi]
    return out


def rgb15(hex_colour):
    r, g, b = (int(hex_colour[i:i + 2], 16) >> 3 for i in (0, 2, 4))
    return r | g << 5 | b << 10


def build():
    files = {}
    # Font: ink on paper, bank 1 (attribute bit 3) and UI palette 7.
    chars = A.FONT_CHARS
    assert len(chars) <= 64 - 0 and FONT_FIRST + len(chars) <= 256
    font = []
    for ch in chars:
        font += tile_bytes(A.font_rows(ch))
    files[ENGINE / 'include/td_font.h'] = (
        '/* Generated by scripts/create_ui_art.py: original bold UI font. */\n'
        'static const char td_chars[]="' + chars.replace('\\', '\\\\').replace('"', '\\"') + '";\n'
        'static const UBYTE td_font[]={' + ','.join(map(str, font)) + '};\n')
    # Art tiles in code order of first use, bank 0 from tile 128.
    names, index = [], {}
    for _, tile, _, _ in A.CODES:
        if tile not in index:
            index[tile] = len(names)
            names.append(tile)
    assert set(names) == set(A.TILES), sorted(set(A.TILES) ^ set(names))
    assert ART_FIRST + len(names) <= 192, 'UI art must stay inside bank-0 tiles 128..191'
    art = []
    for name in names:
        art += tile_bytes(A.TILES[name][1])
    # Glyph tables for character codes 32..255.
    tiles, attrs = [], []
    font_attr = 0x08 | 7
    for code in range(32, 256):
        ch = chr(code)
        if code < 128:
            c = ch.upper()
            k = chars.find(c) if c in chars else 0
            tiles.append(FONT_FIRST + k)
            attrs.append(font_attr)
        elif code - FIRST_CODE < len(A.CODES):
            _, tile, fx, fy = A.CODES[code - FIRST_CODE]
            tiles.append(ART_FIRST + index[tile])
            attrs.append(A.PALETTES[A.TILES[tile][0]] | (0x20 if fx else 0) | (0x40 if fy else 0))
        else:
            tiles.append(FONT_FIRST)
            attrs.append(font_attr)
    assert FIRST_CODE + len(A.CODES) < 0xFF, 'code 0xFF marks an invalidated row cache'
    lines = ['/* Generated by scripts/create_ui_art.py from ui_art.py. Original art. */',
             '#ifndef TD_UI_ART_H', '#define TD_UI_ART_H',
             f'#define TD_UI_ART_FIRST {ART_FIRST}', f'#define TD_UI_ART_TILES {len(names)}',
             f'#define TD_FONT_FIRST {FONT_FIRST}', f'#define TD_FONT_GLYPHS {len(chars)}',
             '/* Character codes for art glyphs; concatenate with string literals. */']
    for k, (name, _, _, _) in enumerate(A.CODES):
        lines.append(f'#define TD_UI_{name} "\\x{FIRST_CODE + k:02x}"')
    # Title illustration: rows 0..8, bank-1 tiles borrowed from 8 while shown.
    grid = A.title_image()
    order = [2, 7, 0, 5]
    title_tiles, title_map, title_attr, seen = [], [], [], {}
    for ty in range(A.TITLE_ROWS):
        for tx in range(20):
            cells = [[grid[ty * 8 + y][tx * 8 + x] for x in range(8)] for y in range(8)]
            used = {c for row in cells for c in row}
            slot = next(s for s in order if used <= set(A.SLOT_COLOURS[s]))
            shades = A.SLOT_COLOURS[slot]
            rows = [''.join('.as#'[shades.index(c)] for c in row) for row in cells]
            data = tuple(tile_bytes(rows))
            if data not in seen:
                seen[data] = len(title_tiles)
                title_tiles.append(data)
            title_map.append(TITLE_FIRST + seen[data])
            title_attr.append(0x08 | slot)
    assert TITLE_FIRST + len(title_tiles) <= 188, 'title art must fit the atlas-owned bank-1 range'
    lines += [f'#define TD_TITLE_FIRST {TITLE_FIRST}', f'#define TD_TITLE_TILES {len(title_tiles)}',
              f'#define TD_TITLE_ROWS {A.TITLE_ROWS}']
    lines += ['#ifdef TD_UI_ART_DATA',
              f'static const UBYTE td_title_tiles[{16 * len(title_tiles)}]={{' + ','.join(str(b) for t in title_tiles for b in t) + '};',
              f'static const UBYTE td_title_map[{len(title_map)}]={{' + ','.join(map(str, title_map)) + '};',
              f'static const UBYTE td_title_attr[{len(title_attr)}]={{' + ','.join(map(str, title_attr)) + '};',
              f'static const UBYTE td_ui_art[{len(art)}]={{' + ','.join(map(str, art)) + '};',
              '/* Window tile and CGB attribute for each character code 32..255. */',
              'static const UBYTE td_glyph_tile[224]={' + ','.join(map(str, tiles)) + '};',
              'static const UBYTE td_glyph_attr[224]={' + ','.join(map(str, attrs)) + '};',
              '/* BG palette 7: menu colours, and the original colours the atlas map was drawn for. */',
              'static const UWORD td_ui_palette[4]={' + ','.join(str(rgb15(c)) for c in A.UI_COLORS) + '};',
              'static const UWORD td_map_palette[4]={' + ','.join(str(rgb15(c)) for c in A.MAP_COLORS) + '};',
              '#endif', '#endif', '']
    files[ENGINE / 'include/td_ui_art.h'] = '\n'.join(lines)
    path = ROOT / 'project/project/palettes/default_ui.gbsres'
    pal = json.loads(path.read_text())
    pal['name'] = pal['defaultName'] = 'Toronto Dispatch UI'
    pal['colors'] = pal['defaultColors'] = list(A.UI_COLORS)
    files[path] = json.dumps(pal, indent=2) + '\n'
    return files, len(names), len(chars), len(title_tiles)


def main():
    files, tiles, glyphs, title = build()
    stale = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
    if '--check' in sys.argv:
        assert not stale, 'UI art outputs are stale: ' + ', '.join(str(p.relative_to(ROOT)) for p in stale)
        print(f'UI art matches its designs: {tiles} art tiles, {glyphs} font glyphs, {len(A.CODES)} glyph codes, {title} title tiles.')
        return
    for path in stale:
        path.write_text(files[path])
    print(f'Wrote {len(stale)} UI outputs: {tiles} art tiles, {glyphs} font glyphs, {len(A.CODES)} glyph codes, {title} title tiles.')


if __name__ == '__main__':
    main()
