"""Register only final reachable original furniture; preserve structural masks."""
import argparse,hashlib,json
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
ENGINE=ROOT/'project/plugins/toronto-driving/engine'
ARTS=['city_art.json',*[f'districts/{name}_art.json' for name in ['west','high_park','east','port_lands','island','north']]]
FILENAMES=['city','west','high_park','east','port_lands','islands','north']
KINDS=['street_sign','light_pole','fence','park_sign','bin','bollard','flowers','bench','yard_crate','bus_stop','crossing_sign']
COLORS=[tuple(bytes.fromhex(c)) for c in ['071821','306850','86c06c','e0f8cf']]

def encode(rows):
 out=[]
 for row in rows:
  shades=[3-int(c) for c in row]
  out.extend([sum((c&1)<<(7-x) for x,c in enumerate(shades)),sum(((c>>1)&1)<<(7-x) for x,c in enumerate(shades))])
 return out

def decompress(text):
 out=[];at=0
 while at<len(text):
  value=int(text[at:at+2],16);at+=2
  if text[at]=='!':count=1;at+=1
  else:
   end=text.index('+',at);count=int(text[at:end],16);at=end+1
  assert count>0;out.extend([value]*count)
 assert len(out)==15616
 return out

def generate():
 from street_scenery import PROPS
 props=[];grounds=[];offsets=[0];counts=[];provenance=[];row_offsets=[]
 for district,(filename,slug) in enumerate(zip(ARTS,FILENAMES)):
  art=json.loads((ROOT/'content'/filename).read_text())
  scene=json.loads((ROOT/f'project/project/scenes/toronto_{slug}/scene.gbsres').read_text())
  collisions=decompress(scene['collisions'])
  bg=json.loads((ROOT/f'project/assets/backgrounds/toronto_{slug}.png.gbsres').read_text())
  attrs=decompress(bg['tileColors'])
  image=Image.open(ROOT/f'project/assets/backgrounds/toronto_{slug}.png').convert('RGB')
  registered=art['scenery']['destructible_furniture'];assert len(registered)<=256
  for n,p in enumerate(registered):
   assert p['id']==n and p['x']%8==p['y']%8==0
   x,y=p['x']//8,p['y']//8;cell=y*128+x
   assert not collisions[cell]&15 and not attrs[cell]&128
   expected=[COLORS[int(c)] for row in PROPS[p['kind']] for c in row]
   assert list(image.crop((p['x'],p['y'],p['x']+8,p['y']+8)).get_flattened_data())==expected,(slug,p)
   ground=encode(p['ground_rows'])
   if ground not in grounds:grounds.append(ground)
   props.append([x,y,KINDS.index(p['kind']),grounds.index(ground)])
  district_props=props[offsets[-1]:]
  assert district_props==sorted(district_props,key=lambda p:(p[1],p[0]))
  assert all(0<=p[1]<122 for p in district_props)
  row_offsets.append([offsets[-1]+sum(p[1]<y for p in district_props) for y in range(123)])
  offsets.append(len(props));counts.append(len(registered))
  provenance.append({'district':district,'source':filename,'count':len(registered),'registry_sha256':hashlib.sha256(json.dumps(registered,sort_keys=True,separators=(',',':')).encode()).hexdigest()})
 assert len(grounds)<256
 lines=['/* Original reachable furniture; generated by create_scenery_data.py. */',
        'static const UWORD td_prop_offsets[8]={'+','.join(map(str,offsets))+'};',
        'static const td_prop_t td_props['+str(len(props))+']={']
 lines+=['    {'+','.join(map(str,p))+'},' for p in props];lines+=['};',
 'static const UBYTE td_prop_ground['+str(len(grounds))+'][16]={']
 lines+=['    {'+','.join(map(str,g))+'},' for g in grounds];lines+=['};']
 # Exact same-bank row prefixes narrow only the lower-bound search domain.
 # No property, order, collision, pixel, runtime bitmap or save field changes.
 for district,rows in enumerate(row_offsets):
  lines+=['static const UWORD td_prop_rows_'+str(district)+'[123]={',
          '    '+','.join(map(str,rows)),'};']
 lines+=['static const UWORD * const td_prop_rows[7]={'+','.join('td_prop_rows_'+str(d) for d in range(7))+'};',
 'static const UBYTE td_prop_flash[8]={0,36,0,129,24,129,0,36};',
 'static const UBYTE td_prop_falling[8]={0,0,66,0,24,66,0,36};',
 'static const UBYTE td_prop_rubble[2][8]={{0,0,0,0,0,16,66,36},{0,0,0,0,0,8,36,66}};']
 return ('\n'.join(lines)+'\n').encode(),{'schema':1,'source':'create_scenery_data.py','districts':provenance,'counts':counts,'total_props':len(props),'underlay_patterns':len(grounds),'native_static_bytes':233,'row_lookup_rom_bytes':7*123*2+7*2,'broken_bits_bytes':(len(props)+7)//8,'active_animations':4,'bkg_bank':1,'scratch_range':[80,97],'max_visible_patches':18,'new_oam_objects':0,'terrain_collision_bytes_changed':0,'structural_buildings_trees_water_destructible':False}

def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
 code,metadata=generate()
 for path,data in [(ENGINE/'include/td_scenery_data.h',code),(ROOT/'content/scenery_runtime.json',(json.dumps(metadata,indent=2)+'\n').encode())]:
  if args.check:assert path.read_bytes()==data,('Stale scenery runtime',path)
  else:path.write_bytes(data)
 print(f"Reachable furniture: {metadata['counts']} across7 districts; {metadata['underlay_patterns']} exact ground patterns; {metadata['broken_bits_bytes']} destruction bytes; no new OBJ")
if __name__=='__main__':main()
