"""Compile original contracts into native game data; no invented map coordinates hidden in ROM."""
from pathlib import Path
import json
from city_layout import location,ROWS,COLS

ROOT=Path(__file__).resolve().parents[1]
ENGINE=ROOT/'project/plugins/toronto-driving/engine'

def main():
    stops=[
        (288,368,'UNION DEPOT',1),(384,368,'ST LAWRENCE',0),(416,368,'DISTILLERY',0),
        (288,288,'CITY HALL',0),(192,288,'QUEEN WEST',0),(192,224,'AGO / GRANGE',0),
        (256,64,'ROM / BLOOR',0),(128,224,'KENSINGTON',0),(64,288,'DUFFERIN',0),
        (480,288,'RIVERSIDE',0),(320,400,'FERRY TERMINAL',3),(416,400,'EAST BAYFRONT',0),
        (320,336,'KING STATION',1),(320,288,'QUEEN STATION',1),(320,224,'DUNDAS STATION',1),
        (320,160,'COLLEGE STATION',1),(320,112,'WELLESLEY',1),(320,64,'BLOOR-YONGE',1),
        (96,64,'OSSINGTON BUS',2),(416,64,'CASTLE FRANK',2),
        (240,520,'HANLANS POINT',3),(352,512,'CENTRE ISLAND',3),(432,496,'WARDS ISLAND',3),
        (192,368,'CN TOWER',0)]
    stops=[(*location(u,v),name,transit) for u,v,name,transit in stops]
    kinds=['PARCEL ROUND','FRAGILE ART','EXPRESS FILES','HEAVY FREIGHT','TRANSIT RELAY','PASSENGER RUN','RETURN PAPERS','ISLAND POST']
    themes=['Market morning','Gallery opening','Office hours','Harbour cargo','Campus mail','Civic shift','Brick and glass','Night dispatch','City circuit']
    quests=[]
    for i in range(72):
        kind=i%8
        # Early contracts teach movement and parking; later rounds span the whole network.
        count=2 if i<3 else 8+(i%3)
        route=[0]
        if kind==7:
            route=[10,20+(i%3),10,20+((i+1)%3),10,20+((i+2)%3),10]
        elif kind==4:
            route=[0,17,15,18,16,19,14,1,23,0]
        else:
            pool=[1,2,3,4,5,6,7,8,9,11,23]
            for j in range(count-1): route.append(pool[(i*3+j*5)%len(pool)])
            if kind==6: route[-1]=0
        if i==0: route=[0,1]
        if i==1: route=[0,5]
        if i==2: route=[0,2]
        vehicle=1 if kind==3 else (0 if kind==5 else 255)
        minimum=0 if i<3 else (3 if kind in (3,4) else 8 if kind==5 else 12 if kind==7 else 0)
        quests.append({'id':f'contract-{i+1:02d}','title':f'{themes[i//8]} {i%8+1}','kind':kinds[kind],'kind_id':kind,'required_vehicle':vehicle,'min_completed':minimum,'route':route,'time_limit_seconds':120 if i<3 else 80+len(route)*(20 if kind==2 else 40),'reward':80+len(route)*35+i*2})
    content={'status':'engine-integrated','scope':'Compressed central Toronto prototype; broad Old Toronto map accuracy and full campaign duration remain release checks','duration_target_minutes':120,'duration_verified':False,'quest_types':kinds,'stops':[{'id':i,'u':s[0],'v':s[1],'name':s[2],'transit':s[3]} for i,s in enumerate(stops)],'quests':quests,'transit':{'line1':{'stops':[0,12,13,14,15,16,17],'period_seconds':18,'fare':3,'source':'https://www.ttc.ca/routes-and-schedules/1/0/15657'},'bus94':{'stops':[18,16,19],'period_seconds':24,'fare':2,'source':'https://www.ttc.ca/routes-and-schedules/94/1/8008'},'ferry':{'stops':[10,20,21,22],'period_seconds':30,'fare':4,'source':'https://www.toronto.ca/explore-enjoy/toronto-island-ferries/getting-around/'},'notice':'Fictional game timetables, fares and compression. Not a TTC trip planner.'}}
    (ROOT/'content/campaign.json').write_text(json.dumps(content,indent=2)+'\n')
    code=['// Generated by scripts/create_campaign.py; original content.','#pragma bank 255','#include <string.h>','#include "td_game.h"','static const td_stop_t td_stops[TD_STOPS] = {']
    for u,v,n,t in stops: code.append(f'  {{{u},{v},"{n}",{t}}},')
    code+=['};','static const td_job_t td_jobs[TD_QUESTS] = {']
    for q in quests:
        title=q['title'][:18].upper(); route=q['route']+[255]*(12-len(q['route']))
        code.append('  {"%s",%d,%d,%d,%d,%d,%d,{%s}},'%(title,q['kind_id'],len(q['route']),q['required_vehicle'],q['min_completed'],q['time_limit_seconds'],q['reward'],','.join(map(str,route))))
    code+=['};','void td_get_stop(UBYTE i,td_stop_t *d) BANKED { if(i<TD_STOPS) memcpy(d,&td_stops[i],sizeof(td_stop_t)); }','void td_get_job(UBYTE i,td_job_t *d) BANKED { if(i<TD_QUESTS) memcpy(d,&td_jobs[i],sizeof(td_job_t)); }',
    'void td_get_street(UWORD u,UWORD v,char *d) BANKED {',
    '  const char *name="TORONTO";',
    '  if(v>816) name="TORONTO ISLANDS";',
    '  else if(v>768) name="QUEENS QUAY";',
    '  else if(v>688) name="FRONT STREET";',
    '  else if(v>608) name="KING STREET";',
    '  else if(v>496) name="QUEEN STREET";',
    '  else if(v>368) name="DUNDAS STREET";',
    '  else if(v>256) name="COLLEGE / CARLTON";',
    '  else if(v>144) name="WELLESLEY / HARBORD";',
    '  else name="BLOOR STREET";',
    '  { const UWORD columns[]={80,208,336,480,560,640,720,816,944};',
    '    const char *roads[]={"DUFFERIN STREET","BATHURST STREET","SPADINA AVENUE","UNIVERSITY AVENUE","BAY STREET","YONGE STREET","JARVIS STREET","PARLIAMENT STREET","BROADVIEW AVENUE"};',
    '    const UWORD rows[]={64,176,288,400,528,640,720,784};',
    '    UWORD nearest_x=65535,nearest_y=65535,delta; UBYTE i,best=0;',
    '    for(i=0;i<9;i++){delta=u>columns[i]?u-columns[i]:columns[i]-u;if(delta<nearest_x){nearest_x=delta;best=i;}}',
    '    for(i=0;i<8;i++){delta=v>rows[i]?v-rows[i]:rows[i]-v;if(delta<nearest_y)nearest_y=delta;}',
    '    if(v<816 && nearest_x<nearest_y)name=roads[best];',
    '  } strcpy(d,name);',
    '}']
    (ENGINE/'src').mkdir(parents=True,exist_ok=True)
    (ENGINE/'src/td_content.c').write_text('\n'.join(code)+'\n')
    # Fixed-size UI cells reuse the MIT starter font, retaining its asset licence.
    font=json.loads((ROOT/'project/original-art/native-cells.json').read_text())['font']['cells']
    chars=' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789:/.-+?<>$%#='
    glyphs={c['character']:c['rows'] for c in font}
    data=[]
    for ch in chars:
        for row in glyphs[ch]:
            bits=sum(1<<(7-i) for i,pixel in enumerate(row) if pixel=='0')
            data.extend((bits,bits))
    (ENGINE/'include/td_font.h').write_text('// Derived from MIT Bench Mono glyphs; see project/ASSET_LICENSE.\nstatic const char td_chars[]="'+chars+'";\nstatic const UBYTE td_font[]={' + ','.join(map(str,data))+'};\n')
    print('Compiled',len(quests),'contracts,',len(stops),'stops and scheduled train/bus/ferry services.')

if __name__=='__main__': main()
