"""Generate the dispatcher radio lines from content/radio.json.

Writes engine/include/td_radio_data.h: every script is a run of pages and
every page is two 17-column lines, word-wrapped here so the engine only
copies characters. The chapter short names for the dispatch board are
checked against the chapters of content/campaign.json.
`--check` verifies the output without writing.
"""
import json
import sys
from pathlib import Path
import ui_art as A

ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / 'project/plugins/toronto-driving/engine'
COLS, LINES = 17, 2
# Scripts the engine indexes as a group, in engine order (job kinds follow
# td_kinds in td_ui.c; chapters 1..8 unlock at 6, 12 .. 48 completions).
GROUPS = {
    'JOB': ['PARCEL', 'FRAGILE', 'EXPRESS', 'FREIGHT', 'RELAY', 'PASSENGER', 'RETURN', 'ISLAND'],
    'DONE': ['0', '1', '2'],
    'CHAPTER': [str(i) for i in range(1, 9)],
    'CHATTER': [str(i) for i in range(8)],
}


def wrap(text):
    """Greedy word wrap; '|' forces a line break."""
    lines = []
    for part in text.split('|'):
        line = ''
        for word in part.split():
            assert len(word) <= COLS, word
            candidate = f'{line} {word}' if line else word
            if len(candidate) <= COLS:
                line = candidate
            else:
                lines.append(line)
                line = word
        lines.append(line)
    assert len(lines) <= LINES, f'page needs {len(lines)} lines: {text!r} -> {lines}'
    return ''.join(l.ljust(COLS) for l in lines).ljust(COLS * LINES)


def c_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def build():
    data = json.loads((ROOT / 'content/radio.json').read_text())
    campaign = json.loads((ROOT / 'content/campaign.json').read_text())
    chapters = []
    for quest in campaign['quests']:
        if quest['chapter'] not in chapters:
            chapters.append(quest['chapter'])
    short = data['chapter_short_names']
    assert len(short) == len(chapters) == (len(campaign['quests']) + 7) // 8, (len(short), len(chapters))
    for i, quest in enumerate(campaign['quests']):
        assert chapters.index(quest['chapter']) == i // 8, 'chapters are groups of eight contracts'
    allowed = set(A.FONT_CHARS)
    scripts = data['scripts']
    order = [name for name in scripts if not any(name.startswith(g + '_') for g in GROUPS)]
    for group, members in GROUPS.items():
        order += [f'{group}_{m}' for m in members]
    assert sorted(order) == sorted(scripts), sorted(set(order) ^ set(scripts))
    pages, first = [], []
    for name in order:
        first.append(len(pages))
        for text in scripts[name]:
            assert set(text) - {'|'} <= allowed, (name, set(text) - allowed)
            pages.append(wrap(text))
    first.append(len(pages))
    assert len(pages) < 256
    for name in short:
        assert len(name) <= 16 and set(name) <= allowed, name
    speaker = f"{data['speaker']} - {data['role']}"
    assert len(speaker) <= COLS and set(speaker) <= allowed
    lines = ['/* Generated by scripts/create_radio.py from content/radio.json. Original dialogue. */',
             '#ifndef TD_RADIO_DATA_H', '#define TD_RADIO_DATA_H',
             f'#define TD_RADIO_COLS {COLS}', f'#define TD_RADIO_PAGE {COLS * LINES}',
             f'#define TD_RADIO_SCRIPTS {len(order)}', f'#define TD_CHAPTERS {len(short)}',
             f'#define TD_RADIO_SPEAKER {c_string(speaker)}']
    for k, name in enumerate(order):
        if not any(name.startswith(g + '_') for g in GROUPS):
            lines.append(f'#define TD_RADIO_{name} {k}')
    for group, members in GROUPS.items():
        lines.append(f'#define TD_RADIO_{group} {order.index(f"{group}_{members[0]}")}')
        lines.append(f'#define TD_RADIO_{group}_COUNT {len(members)}')
    lines += ['#ifdef TD_RADIO_DATA',
              f'static const UBYTE td_radio_first[{len(first)}]={{' + ','.join(map(str, first)) + '};',
              f'static const char td_radio_pages[{len(pages)}][{COLS * LINES}]={{']
    # Exactly 34 characters each: no terminating NUL is stored.
    lines += [f'    {c_string(p)},' for p in pages]
    lines += ['};', f'static const char td_chapter_names[{len(short)}][17]={{' + ','.join(c_string(s) for s in short) + '};',
              '#endif', '#endif', '']
    return {ENGINE / 'include/td_radio_data.h': '\n'.join(lines)}, len(order), len(pages)


def main():
    files, scripts, pages = build()
    stale = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
    if '--check' in sys.argv:
        assert not stale, 'radio lines are stale; run scripts/create_radio.py'
        print(f'Radio lines match content/radio.json: {scripts} scripts, {pages} pages.')
        return
    for path in stale:
        path.write_text(files[path])
    print(f'Wrote {len(stale)} radio output(s): {scripts} scripts, {pages} pages.')


if __name__ == '__main__':
    main()
