/* Generated by scripts/create_hidden_vehicles.py: special vehicles parked
 * beside landmarks (scene, centre in whole pixels, TD_SPECIAL_* kind,
 * heading 0 east or 2 south). */
#ifndef TD_HIDDEN_H
#define TD_HIDDEN_H
#define TD_HIDDEN_COUNT 6
#ifdef TD_HIDDEN_DATA
static const UBYTE td_hidden_scene[TD_HIDDEN_COUNT]={1,1,3,7,14,9};
static const UWORD td_hidden_u[TD_HIDDEN_COUNT]={592,496,256,64,856,328};
static const UWORD td_hidden_v[TD_HIDDEN_COUNT]={856,744,160,344,496,192};
static const UBYTE td_hidden_kind[TD_HIDDEN_COUNT]={6,1,2,3,5,4};
static const UBYTE td_hidden_head[TD_HIDDEN_COUNT]={2,0,2,0,2,2};
#endif
/* Moss Park Armoury: tank in scene 1 at (592,856); Toronto General Hospital: ambulance in scene 1 at (496,744); Old City Hall: fire_truck in scene 3 at (256,160); Roncesvalles Carhouse: bus in scene 7 at (64,344); Carlaw Works: garbage_truck in scene 14 at (856,496); Junction heritage brick block: box_truck in scene 9 at (328,192) */
#endif
