/* Generated by scripts/create_interior_data.py: interior scene pointers. */
#ifndef TD_INTERIOR_SCENES_H
#define TD_INTERIOR_SCENES_H
#include "data/scene_interior_cn_base.h"
#include "data/scene_interior_cn_lookout.h"
#include "data/scene_interior_ago.h"
#include "data/scene_interior_cafe.h"
#include "data/scene_interior_rom.h"
#include "data/scene_interior_eaton.h"
#include "data/scene_interior_union.h"
#include "data/scene_interior_dragon_city.h"
#include "data/scene_interior_chinatown_bakery.h"
#include "data/scene_interior_electronics.h"
#include "data/scene_interior_corner_store.h"
#include "data/scene_interior_diner.h"
#include "data/scene_interior_shop.h"
#include "data/scene_interior_office_lobby.h"
#include "data/scene_interior_pub.h"
#include "data/scene_interior_gallery_hall.h"
#include "data/scene_interior_gallery_art.h"
static const far_ptr_t td_in_scene[TD_INTERIORS]={TO_FAR_PTR_T(scene_interior_cn_base),TO_FAR_PTR_T(scene_interior_cn_lookout),TO_FAR_PTR_T(scene_interior_ago),TO_FAR_PTR_T(scene_interior_cafe),TO_FAR_PTR_T(scene_interior_rom),TO_FAR_PTR_T(scene_interior_eaton),TO_FAR_PTR_T(scene_interior_union),TO_FAR_PTR_T(scene_interior_dragon_city),TO_FAR_PTR_T(scene_interior_chinatown_bakery),TO_FAR_PTR_T(scene_interior_electronics),TO_FAR_PTR_T(scene_interior_corner_store),TO_FAR_PTR_T(scene_interior_diner),TO_FAR_PTR_T(scene_interior_shop),TO_FAR_PTR_T(scene_interior_office_lobby),TO_FAR_PTR_T(scene_interior_pub),TO_FAR_PTR_T(scene_interior_gallery_hall),TO_FAR_PTR_T(scene_interior_gallery_art)};
#endif
