#ifndef TD_PLACES_H
#define TD_PLACES_H
/* Navigation names (td_places.c, generated by scripts/create_places.py):
 * the neighbourhood, landmark and junction around a position. */
#define TD_PLACE_NONE 255
#define TD_PLACE_AREA 0
#define TD_PLACE_MARK 1
#define TD_PLACE_JUNCTION 2
/* A neighbourhood holds until the courier is this far outside it. */
#define TD_AREA_HOLD 16
#define TD_PLACE_NAME 21
void td_get_places(UWORD u,UWORD v,UBYTE *ids) BANKED;
void td_get_place_name(UBYTE kind,UBYTE id,char *d) BANKED;
#endif
