#pragma bank 255
#include "td_streetcar.h"
#include "td_transit.h"
#include "td_district.h"

typedef char td_streetcar_schedule_is_registered[
    (TD_TRANSIT_QUEEN_FIRST==43 && TD_TRANSIT_QUEEN_COUNT==8 &&
     TD_TRANSIT_QUEEN_PERIOD==64 && TD_TRANSIT_QUEEN_HOP_SECONDS==4 &&
     TD_STREETCAR_PERIOD_TICKS==TD_TRANSIT_QUEEN_PERIOD*60 &&
     TD_DISTRICT_PIXEL_WIDTH==1024 && TD_DISTRICT_PIXEL_HEIGHT==976) ? 1 : -1];
typedef struct { UWORD u,v; UBYTE district; } td_streetcar_point_t;

/* A seam has zero travel length: the existing legal scene entrance maps
 * local1000 to local24. Each other edge is cardinal. Opposite Queen lanes
 * remain eight pixels from the centreline, including East's offset miter. */
static const td_streetcar_point_t td_streetcar_paths[16][4]={
    {{836,536,TD_DISTRICT_WEST},{1000,536,TD_DISTRICT_WEST},
     {24,536,TD_DISTRICT_CITY},{116,536,TD_DISTRICT_CITY}},
    {{116,536,TD_DISTRICT_CITY},{372,536,TD_DISTRICT_CITY}},
    {{372,536,TD_DISTRICT_CITY},{676,536,TD_DISTRICT_CITY}},
    {{676,536,TD_DISTRICT_CITY},{980,536,TD_DISTRICT_CITY}},
    {{980,536,TD_DISTRICT_CITY},{1000,536,TD_DISTRICT_CITY},
     {24,536,TD_DISTRICT_EAST},{128,536,TD_DISTRICT_EAST}},
    {{128,536,TD_DISTRICT_EAST},{680,536,TD_DISTRICT_EAST},
     {680,504,TD_DISTRICT_EAST},{780,504,TD_DISTRICT_EAST}},
    {{780,504,TD_DISTRICT_EAST},{880,504,TD_DISTRICT_EAST}},
    {{880,488,TD_DISTRICT_EAST},{780,488,TD_DISTRICT_EAST}},
    {{780,488,TD_DISTRICT_EAST},{664,488,TD_DISTRICT_EAST},
     {664,520,TD_DISTRICT_EAST},{128,520,TD_DISTRICT_EAST}},
    {{128,520,TD_DISTRICT_EAST},{24,520,TD_DISTRICT_EAST},
     {1000,520,TD_DISTRICT_CITY},{980,520,TD_DISTRICT_CITY}},
    {{980,520,TD_DISTRICT_CITY},{676,520,TD_DISTRICT_CITY}},
    {{676,520,TD_DISTRICT_CITY},{372,520,TD_DISTRICT_CITY}},
    {{372,520,TD_DISTRICT_CITY},{116,520,TD_DISTRICT_CITY}},
    {{116,520,TD_DISTRICT_CITY},{24,520,TD_DISTRICT_CITY},
     {1000,520,TD_DISTRICT_WEST},{836,520,TD_DISTRICT_WEST}},
    {{880,504,TD_DISTRICT_EAST},{880,488,TD_DISTRICT_EAST}},
    {{836,520,TD_DISTRICT_WEST},{836,536,TD_DISTRICT_WEST}}
};
static const UBYTE td_streetcar_path_counts[16]={4,2,2,2,4,4,2,2,4,4,2,2,2,4,2,2};
/* BEGIN GENERATED STREETCAR PROGRESS */
/* Generated by scripts/create_streetcar_progress.py from the paths/counts
 * above. Exact floor(length*tick/120), including both endpoints. All
 * values and near pointers live in this same bank; no persistent WRAM. */
static const UWORD td_streetcar_progress_256[121]={
    0,2,4,6,8,10,12,14,17,19,21,23,
    25,27,29,32,34,36,38,40,42,44,46,49,
    51,53,55,57,59,61,64,66,68,70,72,74,
    76,78,81,83,85,87,89,91,93,96,98,100,
    102,104,106,108,110,113,115,117,119,121,123,125,
    128,130,132,134,136,138,140,142,145,147,149,151,
    153,155,157,160,162,164,166,168,170,172,174,177,
    179,181,183,185,187,189,192,194,196,198,200,202,
    204,206,209,211,213,215,217,219,221,224,226,228,
    230,232,234,236,238,241,243,245,247,249,251,253,
    256,
};
static const UWORD td_streetcar_progress_1600[121]={
    0,13,26,40,53,66,80,93,106,120,133,146,
    160,173,186,200,213,226,240,253,266,280,293,306,
    320,333,346,360,373,386,400,413,426,440,453,466,
    480,493,506,520,533,546,560,573,586,600,613,626,
    640,653,666,680,693,706,720,733,746,760,773,786,
    800,813,826,840,853,866,880,893,906,920,933,946,
    960,973,986,1000,1013,1026,1040,1053,1066,1080,1093,1106,
    1120,1133,1146,1160,1173,1186,1200,1213,1226,1240,1253,1266,
    1280,1293,1306,1320,1333,1346,1360,1373,1386,1400,1413,1426,
    1440,1453,1466,1480,1493,1506,1520,1533,1546,1560,1573,1586,
    1600,
};
static const UWORD td_streetcar_progress_1984[121]={
    0,16,33,49,66,82,99,115,132,148,165,181,
    198,214,231,248,264,281,297,314,330,347,363,380,
    396,413,429,446,462,479,496,512,529,545,562,578,
    595,611,628,644,661,677,694,710,727,744,760,777,
    793,810,826,843,859,876,892,909,925,942,958,975,
    992,1008,1025,1041,1058,1074,1091,1107,1124,1140,1157,1173,
    1190,1206,1223,1240,1256,1273,1289,1306,1322,1339,1355,1372,
    1388,1405,1421,1438,1454,1471,1488,1504,1521,1537,1554,1570,
    1587,1603,1620,1636,1653,1669,1686,1702,1719,1736,1752,1769,
    1785,1802,1818,1835,1851,1868,1884,1901,1917,1934,1950,1967,
    1984,
};
static const UWORD td_streetcar_progress_4096[121]={
    0,34,68,102,136,170,204,238,273,307,341,375,
    409,443,477,512,546,580,614,648,682,716,750,785,
    819,853,887,921,955,989,1024,1058,1092,1126,1160,1194,
    1228,1262,1297,1331,1365,1399,1433,1467,1501,1536,1570,1604,
    1638,1672,1706,1740,1774,1809,1843,1877,1911,1945,1979,2013,
    2048,2082,2116,2150,2184,2218,2252,2286,2321,2355,2389,2423,
    2457,2491,2525,2560,2594,2628,2662,2696,2730,2764,2798,2833,
    2867,2901,2935,2969,3003,3037,3072,3106,3140,3174,3208,3242,
    3276,3310,3345,3379,3413,3447,3481,3515,3549,3584,3618,3652,
    3686,3720,3754,3788,3822,3857,3891,3925,3959,3993,4027,4061,
    4096,
};
static const UWORD td_streetcar_progress_4864[121]={
    0,40,81,121,162,202,243,283,324,364,405,445,
    486,526,567,608,648,689,729,770,810,851,891,932,
    972,1013,1053,1094,1134,1175,1216,1256,1297,1337,1378,1418,
    1459,1499,1540,1580,1621,1661,1702,1742,1783,1824,1864,1905,
    1945,1986,2026,2067,2107,2148,2188,2229,2269,2310,2350,2391,
    2432,2472,2513,2553,2594,2634,2675,2715,2756,2796,2837,2877,
    2918,2958,2999,3040,3080,3121,3161,3202,3242,3283,3323,3364,
    3404,3445,3485,3526,3566,3607,3648,3688,3729,3769,3810,3850,
    3891,3931,3972,4012,4053,4093,4134,4174,4215,4256,4296,4337,
    4377,4418,4458,4499,4539,4580,4620,4661,4701,4742,4782,4823,
    4864,
};
static const UWORD td_streetcar_progress_10944[121]={
    0,91,182,273,364,456,547,638,729,820,912,1003,
    1094,1185,1276,1368,1459,1550,1641,1732,1824,1915,2006,2097,
    2188,2280,2371,2462,2553,2644,2736,2827,2918,3009,3100,3192,
    3283,3374,3465,3556,3648,3739,3830,3921,4012,4104,4195,4286,
    4377,4468,4560,4651,4742,4833,4924,5016,5107,5198,5289,5380,
    5472,5563,5654,5745,5836,5928,6019,6110,6201,6292,6384,6475,
    6566,6657,6748,6840,6931,7022,7113,7204,7296,7387,7478,7569,
    7660,7752,7843,7934,8025,8116,8208,8299,8390,8481,8572,8664,
    8755,8846,8937,9028,9120,9211,9302,9393,9484,9576,9667,9758,
    9849,9940,10032,10123,10214,10305,10396,10488,10579,10670,10761,10852,
    10944,
};
static const UWORD * const td_streetcar_progress_routes[16]={
    td_streetcar_progress_4096,td_streetcar_progress_4096,td_streetcar_progress_4864,td_streetcar_progress_4864,
    td_streetcar_progress_1984,td_streetcar_progress_10944,td_streetcar_progress_1600,td_streetcar_progress_1600,
    td_streetcar_progress_10944,td_streetcar_progress_1984,td_streetcar_progress_4864,td_streetcar_progress_4864,
    td_streetcar_progress_4096,td_streetcar_progress_4096,td_streetcar_progress_256,td_streetcar_progress_256,
};
typedef char td_streetcar_progress_routes_match_paths[
    (sizeof(td_streetcar_progress_routes)/sizeof(td_streetcar_progress_routes[0])==
     sizeof(td_streetcar_path_counts))?1:-1];
#ifdef __SDCC
typedef char td_streetcar_progress_near_pointer_fits[
    (sizeof(td_streetcar_progress_routes[0])==2)?1:-1];
#endif
/* END GENERATED STREETCAR PROGRESS */
static const UWORD td_streetcar_stop_u[8]={836,116,372,676,980,128,780,880};
static const UBYTE td_streetcar_stop_district[8]={
    TD_DISTRICT_WEST,TD_DISTRICT_CITY,TD_DISTRICT_CITY,TD_DISTRICT_CITY,
    TD_DISTRICT_CITY,TD_DISTRICT_EAST,TD_DISTRICT_EAST,TD_DISTRICT_EAST
};

static UWORD td_streetcar_distance(UWORD a,UWORD b){return a>b?a-b:b-a;}
static UWORD td_streetcar_clock(UWORD seconds,UBYTE subsecond){
    return (seconds&63)*60+subsecond;
}
static UBYTE td_streetcar_route(UBYTE section){
    return section<7?section:section==7?14:section<15?section-1:15;
}
static UWORD td_streetcar_edge(const td_streetcar_point_t *a,
                              const td_streetcar_point_t *b){
    if(a->district!=b->district)return 0;
    return (td_streetcar_distance(a->u,b->u)+td_streetcar_distance(a->v,b->v))<<4;
}
static UWORD td_streetcar_progress(UBYTE route,UBYTE tick){
    /* Public clock/sweep validation proves route0..15 and tick0..120. The
     * same-bank ROM pointers avoid both repeated division and a row-stride
     * multiplication; the authored edge/seam ownership below is unchanged. */
    return td_streetcar_progress_routes[route][tick];
}
static UBYTE td_streetcar_heading(const td_streetcar_point_t *a,
                                 const td_streetcar_point_t *b){
    return a->u!=b->u?(a->u<b->u?0:8):(a->v<b->v?4:12);
}
static void td_streetcar_dwell(UBYTE index,UBYTE direction,td_streetcar_pose_t *pose){
    pose->u=td_streetcar_stop_u[index]<<4;
    pose->v=(index<6?(direction?520:536):(direction?488:504))<<4;
    pose->district=td_streetcar_stop_district[index];
    pose->heading=direction?8:0;pose->frame=direction?6:4;
    pose->stop=TD_TRANSIT_QUEEN_FIRST+index;pose->direction=direction;pose->doors=1;
}
static void td_streetcar_edge_pose(const td_streetcar_point_t *a,
                                  const td_streetcar_point_t *b,UWORD distance,
                                  td_streetcar_pose_t *pose){
    pose->u=a->u<<4;pose->v=a->v<<4;pose->district=a->district;
    pose->heading=td_streetcar_heading(a,b);
    if(pose->heading==0)pose->u+=distance;
    else if(pose->heading==8)pose->u-=distance;
    else if(pose->heading==4)pose->v+=distance;
    else pose->v-=distance;
    pose->frame=pose->heading>>2;
    pose->stop=TD_TRANSIT_NONE;pose->doors=0;
}
static void td_streetcar_travel(UBYTE route,UBYTE tick,td_streetcar_pose_t *pose){
    UBYTE i;UWORD distance=td_streetcar_progress(route,tick),edge;
    for(i=1;i<td_streetcar_path_counts[route];i++){
        edge=td_streetcar_edge(&td_streetcar_paths[route][i-1],&td_streetcar_paths[route][i]);
        if(!edge)continue;
        if(distance<=edge){
            td_streetcar_edge_pose(&td_streetcar_paths[route][i-1],&td_streetcar_paths[route][i],distance,pose);
            return;
        }
        distance-=edge;
    }
}
static void td_streetcar_pose_section(UBYTE section,UBYTE tick,td_streetcar_pose_t *pose){
    UBYTE direction=section>=8;
    if(tick<120)td_streetcar_dwell(direction?15-section:section,direction,pose);
    else{
        pose->direction=direction;
        td_streetcar_travel(td_streetcar_route(section),tick-120,pose);
    }
}
static void td_streetcar_pose_local(UWORD phase,td_streetcar_pose_t *pose){
    td_streetcar_pose_section(phase/240,phase%240,pose);
}
static UBYTE td_streetcar_bounds_local(const td_streetcar_pose_t *pose,td_streetcar_box_t *box){
    UWORD half_u,half_v;
    if((pose->heading&3)||pose->heading>12||
       (pose->district!=TD_DISTRICT_CITY&&pose->district!=TD_DISTRICT_WEST&&pose->district!=TD_DISTRICT_EAST))return FALSE;
    half_u=(pose->heading&4?6:14)*16;half_v=(pose->heading&4?14:6)*16;
    if(pose->u<half_u||pose->v<half_v||
       pose->u>TD_DISTRICT_PIXEL_WIDTH*16-half_u||
       pose->v>TD_DISTRICT_PIXEL_HEIGHT*16-half_v)return FALSE;
    box->left=pose->u-half_u;box->right=pose->u+half_u-1;
    box->top=pose->v-half_v;box->bottom=pose->v+half_v-1;
    box->district=pose->district;return TRUE;
}
static UBYTE td_streetcar_box_valid(const td_streetcar_box_t *box){
    return box->district<TD_DISTRICT_COUNT&&box->left<=box->right&&box->top<=box->bottom&&
        box->right<TD_DISTRICT_PIXEL_WIDTH*16&&box->bottom<TD_DISTRICT_PIXEL_HEIGHT*16;
}
static UBYTE td_streetcar_boxes_hit(const td_streetcar_box_t *a,const td_streetcar_box_t *b){
    return a->district==b->district&&a->left<=b->right&&a->right>=b->left&&
        a->top<=b->bottom&&a->bottom>=b->top;
}
static UBYTE td_streetcar_travel_hit(UBYTE route,UBYTE first,UBYTE last,
                                    const td_streetcar_box_t *box){
    UBYTE i,prior=0;UWORD low,high,edge,start=0,a,b;
    td_streetcar_pose_t p,q;td_streetcar_box_t swept;
    low=td_streetcar_progress(route,first);high=td_streetcar_progress(route,last);
    for(i=1;i<td_streetcar_path_counts[route];i++){
        edge=td_streetcar_edge(&td_streetcar_paths[route][i-1],&td_streetcar_paths[route][i]);
        if(!edge)continue;
        /* At an exact shared endpoint the preceding edge owns the pose.
         * Never connect the old and new local coordinates across a seam. */
        if(low<=start+edge&&high>=start&&(!prior||high>start)&&
           box->district==td_streetcar_paths[route][i-1].district){
            a=low>start?low-start:0;b=high<start+edge?high-start:edge;
            td_streetcar_edge_pose(&td_streetcar_paths[route][i-1],&td_streetcar_paths[route][i],a,&p);
            td_streetcar_edge_pose(&td_streetcar_paths[route][i-1],&td_streetcar_paths[route][i],b,&q);
            td_streetcar_bounds_local(&p,&swept);
            if(q.u>p.u)swept.right+=q.u-p.u;else swept.left-=p.u-q.u;
            if(q.v>p.v)swept.bottom+=q.v-p.v;else swept.top-=p.v-q.v;
            if(td_streetcar_boxes_hit(&swept,box))return TRUE;
        }
        start+=edge;prior=1;
    }
    return FALSE;
}
static UBYTE td_streetcar_range_hit(UWORD first,UWORD last,const td_streetcar_box_t *box){
    UBYTE section=0,route,direction;UWORD base=0,a,b;td_streetcar_pose_t pose;td_streetcar_box_t body;
    /* A boundary can belong to the previous travel endpoint and the next
       dwell. Include both; a full-cycle query still visits all16 sections. */
    while(section<15&&base+240<first){section++;base+=240;}
    for(;section<16&&base<=last;section++,base+=240){
        direction=section>=8;
        if(first<=base+119&&last>=base){
            td_streetcar_dwell(direction?15-section:section,direction,&pose);
            td_streetcar_bounds_local(&pose,&body);
            if(td_streetcar_boxes_hit(&body,box))return TRUE;
        }
        if(first<=base+240&&last>=base+120){
            a=first>base+120?first-base-120:0;b=last<base+240?last-base-120:120;
            route=td_streetcar_route(section);
            if(td_streetcar_travel_hit(route,a,b,box))return TRUE;
        }
    }
    return FALSE;
}

UBYTE td_streetcar_pose(UWORD seconds,UBYTE subsecond,td_streetcar_pose_t *pose) BANKED {
    td_streetcar_pose_t value;
    if(!pose||subsecond>=60)return FALSE;
    td_streetcar_pose_section((seconds&63)>>2,(seconds&3)*60+subsecond,&value);
    *pose=value;return TRUE;
}
UBYTE td_streetcar_ride(UBYTE origin,UBYTE target,UBYTE ride_left,UWORD seconds,
                       UBYTE subsecond,td_streetcar_pose_t *pose) BANKED {
    UBYTE source,dest,direction,duration;UWORD phase,first,last;td_streetcar_pose_t value;
    if(!pose||subsecond>=60||!ride_left||ride_left>28||origin<TD_TRANSIT_QUEEN_FIRST||
       target<TD_TRANSIT_QUEEN_FIRST||origin>=TD_TRANSIT_QUEEN_FIRST+8||
       target>=TD_TRANSIT_QUEEN_FIRST+8||origin==target)return FALSE;
    source=origin-TD_TRANSIT_QUEEN_FIRST;dest=target-TD_TRANSIT_QUEEN_FIRST;direction=source>dest;
    duration=(source>dest?source-dest:dest-source)*4;
    if(ride_left>duration)return FALSE;
    first=((direction?32+(7-source)*4:source*4)+duration-ride_left)*60;
    last=first+120;
    phase=td_streetcar_clock(seconds,subsecond);
    if(phase>=first&&phase<last)td_streetcar_pose_section((seconds&63)>>2,(seconds&3)*60+subsecond,&value);
    else if(ride_left==1)td_streetcar_dwell(dest,direction,&value);
    else return FALSE;
    *pose=value;return TRUE;
}
UBYTE td_streetcar_destination(UBYTE origin,UBYTE target,td_streetcar_pose_t *pose) BANKED {
    td_streetcar_pose_t value;
    if(!pose||origin<TD_TRANSIT_QUEEN_FIRST||target<TD_TRANSIT_QUEEN_FIRST||
       origin>=TD_TRANSIT_QUEEN_FIRST+8||target>=TD_TRANSIT_QUEEN_FIRST+8||origin==target)return FALSE;
    td_streetcar_dwell(target-TD_TRANSIT_QUEEN_FIRST,origin>target,&value);
    *pose=value;return TRUE;
}
UBYTE td_streetcar_bounds(const td_streetcar_pose_t *pose,td_streetcar_box_t *box) BANKED {
    td_streetcar_box_t value;
    if(!pose||!box||!td_streetcar_bounds_local(pose,&value))return FALSE;
    *box=value;return TRUE;
}
UBYTE td_streetcar_sweep(UWORD seconds,UBYTE subsecond,UWORD elapsed,
                        const td_streetcar_box_t *box) BANKED {
    UWORD phase,first;td_streetcar_pose_t pose;td_streetcar_box_t body;
    if(!box||subsecond>=60||!td_streetcar_box_valid(box))return TD_STREETCAR_INVALID;
    phase=td_streetcar_clock(seconds,subsecond);
    if(!elapsed){
        td_streetcar_pose_local(phase,&pose);td_streetcar_bounds_local(&pose,&body);
        return td_streetcar_boxes_hit(&body,box);
    }
    if(elapsed>=TD_STREETCAR_PERIOD_TICKS)return td_streetcar_range_hit(0,TD_STREETCAR_PERIOD_TICKS,box);
    first=phase>=elapsed?phase-elapsed:phase+TD_STREETCAR_PERIOD_TICKS-elapsed;
    return first<=phase?td_streetcar_range_hit(first,phase,box):
        td_streetcar_range_hit(first,TD_STREETCAR_PERIOD_TICKS,box)||td_streetcar_range_hit(0,phase,box);
}
