/* Generated by scripts/create_atlas.py; original native ground schematic. */
#ifndef TD_ATLAS_H
#define TD_ATLAS_H
#include <gbdk/platform.h>
#define TD_ATLAS_SCALE 8
#define TD_ATLAS_WIDTH_PIXELS 512
#define TD_ATLAS_HEIGHT_PIXELS 122
#define TD_ATLAS_TILE_WIDTH 64
#define TD_ATLAS_TILE_HEIGHT 16
#define TD_ATLAS_PATTERNS 457
#define TD_ATLAS_VIEW_WIDTH 20
#define TD_ATLAS_VIEW_HEIGHT 12
#define TD_ATLAS_VISIBLE_LIMIT 172
#define TD_ATLAS_WORST_VISIBLE 161
#define TD_ATLAS_SOLID 0
#define TD_ATLAS_ROAD 1
#define TD_ATLAS_WALK 2
#define TD_ATLAS_WATER 3

/* All output buffers must reside in WRAM. FALSE leaves every output unchanged.
 * Atlas positions are whole MAP pixels, never GBVM Q5 camera coordinates. */
UBYTE td_atlas_bounds(UWORD *width_pixels,UWORD *height_pixels) BANKED;
/* Local input coordinates are whole WORLD pixels within the registered district. */
UBYTE td_atlas_position(UBYTE district,UWORD local_u,UWORD local_v,UWORD *x,UWORD *y) BANKED;
/* Tile coordinates; count1..20, no row wrapping. IDs index the pattern dictionary. */
UBYTE td_atlas_row(UBYTE tile_x,UBYTE tile_y,UBYTE count,UWORD *patterns) BANKED;
/* One16-byte Game Boy2bpp tile, low/high bitplanes interleaved per row. */
UBYTE td_atlas_pattern(UWORD id,UBYTE *tile16) BANKED;
/* A nineteen-byte terminated name. Padding and unregistered areas return FALSE. */
UBYTE td_atlas_district(UWORD x,UWORD y,char *name19) BANKED;
#endif
