"""Generate the hidden special vehicles (engine/include/td_hidden.h).

A few special vehicles stand parked beside fitting landmarks for the
courier to find and take: an army tank at the Moss Park Armoury, an
ambulance at Toronto General, a fire truck at Old City Hall, a TTC bus at
the Roncesvalles Carhouse, a garbage truck at Carlaw Works and a box truck
by the Junction's brick block. Each spot is the clear lot or lawn nearest
the landmark (never a road lane, so traffic loops stay free) where the
32 x 16 (or 16 x 32) body and a tile round it are open ground, all inside
one scene, and nothing drawn over sprites (a canopy, a roof edge or upper
floors) covers it, so it stands in plain view. The engine parks the vehicle there when the courier comes near
(td_life.c).

`--check` verifies the header without writing.
"""
import json
import sys
from pathlib import Path
import world2x

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'project/plugins/toronto-driving/engine/include/td_hidden.h'
KINDS = ('ambulance', 'fire_truck', 'bus', 'box_truck', 'garbage_truck', 'tank')
# (plan district, landmark name, kind)
HIDDEN = [
    (0, 'Moss Park Armoury', 'tank'),
    (0, 'Toronto General Hospital', 'ambulance'),
    (0, 'Old City Hall', 'fire_truck'),
    (1, 'Roncesvalles Carhouse', 'bus'),
    (3, 'Carlaw Works', 'garbage_truck'),
    (2, 'Junction heritage brick block', 'box_truck'),
]


def landmark_rect(old_id, name):
    if old_id == 0:
        data = json.loads((ROOT / 'content/city_art.json').read_text())
        for d in data['districts']:
            if d['name'] == name:
                return d['rect']
    else:
        slug = {1: 'west', 2: 'high_park', 3: 'east'}[old_id]
        data = json.loads((ROOT / f'content/districts/{slug}_art.json').read_text())
        for l in data['world']['landmarks']:
            if l['name'] == name:
                return [l['x'], l['y'], l['width'], l['depth']]
    raise KeyError(name)


_ATTRS = {}


def covered(new_id, l, r, t, b):
    """Any tile of the scene-local tile box carries background priority."""
    if new_id not in _ATTRS:
        _ATTRS[new_id] = json.loads((ROOT / 'project/original-art' / f'{world2x.scene_slug(new_id)}_attributes.json').read_text())
    attrs, tw = _ATTRS[new_id], world2x.SCENE_TW
    return any(attrs[ty * tw + tx] & 0x80 for ty in range(t, b + 1) for tx in range(l, r + 1))


def spot(old_id, rect):
    """Nearest clear parking spot (centre, heading) to the landmark's face."""
    grid = world2x.world_grid(old_id)
    tw = world2x.WORLD_TW
    x, y, w, h = rect
    fx, fy = x + w // 2, y + h + 8
    best = None
    for cy in range(max(16, y - 160), min(world2x.WORLD_H - 16, y + h + 160), 8):
        for cx in range(max(24, x - 160), min(world2x.WORLD_W - 24, x + w + 160), 8):
            for head, (hw, hh) in ((0, (16, 8)), (2, (8, 16))):
                l, r, t, b = (cx - hw - 8) // 8, (cx + hw + 7) // 8, (cy - hh - 8) // 8, (cy + hh + 7) // 8
                body_l, body_r, body_t, body_b = (cx - hw) // 8, (cx + hw - 1) // 8, (cy - hh) // 8, (cy + hh - 1) // 8
                ok = True
                for ty in range(t, b + 1):
                    for tx in range(l, r + 1):
                        c = grid[ty * tw + tx]
                        inside = body_l <= tx <= body_r and body_t <= ty <= body_b
                        if (inside and c != 16) or (not inside and c not in (0, 16)):
                            ok = False
                            break
                    if not ok:
                        break
                if not ok:
                    continue
                new_id, u, v = world2x.scene_of(old_id, cx, cy)
                # Whole body and margin inside that scene, clear of its edges.
                if not (40 <= u <= world2x.SCENE_W - 40 and 40 <= v <= world2x.SCENE_H - 40):
                    continue
                if covered(new_id, (u - hw - 8) // 8, (u + hw + 7) // 8, (v - hh - 24) // 8, (v + hh + 7) // 8):
                    continue
                d = abs(cx - fx) + abs(cy - fy) + (0 if head == 0 else 4)
                if best is None or d < best[0]:
                    best = (d, new_id, u, v, head)
    assert best, ('no clear spot', old_id, rect)
    return best[1:]


def build():
    rows = []
    for old_id, name, kind in HIDDEN:
        scene, u, v, head = spot(old_id, landmark_rect(old_id, name))
        rows.append((scene, u, v, KINDS.index(kind) + 1, head, name))
    lines = ['/* Generated by scripts/create_hidden_vehicles.py: special vehicles parked',
             ' * beside landmarks (scene, centre in whole pixels, TD_SPECIAL_* kind,',
             ' * heading 0 east or 2 south). */',
             '#ifndef TD_HIDDEN_H', '#define TD_HIDDEN_H', f'#define TD_HIDDEN_COUNT {len(rows)}', '#ifdef TD_HIDDEN_DATA']
    lines.append('static const UBYTE td_hidden_scene[TD_HIDDEN_COUNT]={' + ','.join(str(r[0]) for r in rows) + '};')
    lines.append('static const UWORD td_hidden_u[TD_HIDDEN_COUNT]={' + ','.join(str(r[1]) for r in rows) + '};')
    lines.append('static const UWORD td_hidden_v[TD_HIDDEN_COUNT]={' + ','.join(str(r[2]) for r in rows) + '};')
    lines.append('static const UBYTE td_hidden_kind[TD_HIDDEN_COUNT]={' + ','.join(str(r[3]) for r in rows) + '};')
    lines.append('static const UBYTE td_hidden_head[TD_HIDDEN_COUNT]={' + ','.join(str(r[4]) for r in rows) + '};')
    lines += ['#endif', '/* ' + '; '.join(f'{r[5]}: {KINDS[r[3] - 1]} in scene {r[0]} at ({r[1]},{r[2]})' for r in rows) + ' */',
              '#endif', '']
    return '\n'.join(lines)


def main():
    text = build()
    if '--check' in sys.argv:
        assert OUT.read_text() == text, 'hidden vehicles are stale; run scripts/create_hidden_vehicles.py'
        print(f'Hidden vehicles match their landmarks: {len(HIDDEN)} parked.')
        return
    OUT.write_text(text)
    print(f'Wrote {OUT.relative_to(ROOT)}: {len(HIDDEN)} hidden vehicles.')
    print(text.split('/* ')[-1])


if __name__ == '__main__':
    main()
