"""Generate the overlay sprite tiles (td_overlay_data.h): the police
helicopter, sharks, rain, clouds and their shadows, sun rays and gulls.

These are drawn straight into OAM by td_overlay.c rather than as GBVM
actors, from the ten 8x16 tile pairs at bank-0 tiles 236..255 that the UI
art leaves free. Each design is the left half (8 x 16) of a 16 x 16 figure
whose right half is its mirror image, or a single 8 x 16 sprite. Colours:
'.' transparent, 1 light, 2 mid, 3 dark (the OBJ palette's order); the
engine picks the palette per sprite. Original pixel art.

`--check` verifies the header without writing.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'project/plugins/toronto-driving/engine/include/td_overlay_data.h'
FIRST = 236

# (name, rows): sixteen rows of eight.
DESIGNS = [
    # Police helicopter from above, nose north: left half of a 16x16 body
    # with the tail boom running south; two rotor positions.
    ('heli_a', ["3.......", ".3......", "..3.....", "...3...3", "....3.32", ".....322",
                "......32", ".....322", "....3222", "...3.322", "..3..322", ".3....32",
                "3......3", ".......3", "......32", ".......3"]),
    ('heli_b', ["........", "........", "........", ".......3", "......32", ".....322",
                "33333332", ".....322", "....3222", ".....322", ".....322", "......32",
                ".......3", ".......3", "......32", ".......3"]),
    # Shark fin cutting the water, with its wake (moving west; flipped east).
    ('shark_a', ["........", "........", "........", "....3...", "...33...", "..333...",
                 ".3332...", ".3332...", "33322...", "33322111", "11111...", "..11....",
                 "........", "........", "........", "........"]),
    ('shark_b', ["........", "........", "........", "....3...", "...33...", "..333...",
                 ".3332...", "33322...", "33322...", "33322.11", ".1111111", "...111..",
                 "........", "........", "........", "........"]),
    # Rain: two falling streaks.
    ('rain', [".....1..", "....12..", "....2...", "...2....", "........", "........",
              "........", "........", "..1.....", ".12.....", ".2......", "2.......",
              "........", "........", "........", "........"]),
    # Cloud puff (left half) and its dithered shadow on the ground.
    ('cloud', ["........", "........", ".....111", "...11111", "..111111", ".1111111",
               ".1111111", "11111111", "11111111", "11111111", ".1111111", "..111111",
               "...11111", "........", "........", "........"]),
    ('cloud_shadow', ["........", "........", ".....3.3", "...3.3.3", "..3.3.3.", ".3.3.3.3",
                      "..3.3.3.", ".3.3.3.3", "3.3.3.3.", ".3.3.3.3", "..3.3.3.", "...3.3.3",
                      "....3.3.", "........", "........", "........"]),
    # A shaft of sunlight (falls from the top-left).
    ('sun_ray', ["1.......", ".1......", "1.1.....", ".1.1....", "..1.1...", "...1.1..",
                 "....1.1.", ".....1.1", "......1.", ".......1", "........", "1.......",
                 ".1......", "..1.....", "...1....", "....1..."]),
    # A gull gliding and flapping (wings span the 8x16 sprite across).
    ('gull_a', ["........", "........", "........", "........", "3......3", "11....11",
                ".111111.", "...11...", "...33...", "........", "........", "........",
                "........", "........", "........", "........"]),
    ('gull_b', ["........", "........", "........", "........", "........", "........",
                "...11...", ".111111.", "11.33.11", "3......3", "........", "........",
                "........", "........", "........", "........"]),
]


def tile_bytes(rows):
    out = []
    for row in rows:
        lo = hi = 0
        for x, c in enumerate(row):
            v = 0 if c == '.' else int(c)
            lo |= (v & 1) << (7 - x)
            hi |= (v >> 1) << (7 - x)
        out += [lo, hi]
    return out


def build():
    assert len(DESIGNS) * 2 <= 256 - FIRST
    lines = ['/* Generated by scripts/create_overlay.py: overlay sprite tiles (helicopter,',
             ' * sharks, rain, clouds, sun rays, gulls). Original art. */',
             '#ifndef TD_OVERLAY_DATA_H', '#define TD_OVERLAY_DATA_H',
             f'#define TD_OVERLAY_FIRST {FIRST}', f'#define TD_OVERLAY_TILES {len(DESIGNS) * 2}']
    data = []
    for k, (name, rows) in enumerate(DESIGNS):
        assert len(rows) == 16 and all(len(r) == 8 and set(r) <= set('.123') for r in rows), name
        lines.append(f'#define TD_OV_{name.upper()} {FIRST + 2 * k}')
        data += tile_bytes(rows)
    lines += ['#ifdef TD_OVERLAY_DATA',
              f'static const UBYTE td_overlay_tiles[{len(data)}]={{']
    lines += ['    ' + ','.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',' for i in range(0, len(data), 16)]
    lines += ['};', '#endif', '#endif', '']
    return '\n'.join(lines)


def main():
    text = build()
    if '--check' in sys.argv:
        assert OUT.read_text() == text, 'overlay tiles are stale; run scripts/create_overlay.py'
        print(f'Overlay sprite tiles match their art: {len(DESIGNS)} designs.')
        return
    OUT.write_text(text)
    print(f'Wrote {OUT.relative_to(ROOT)}: {len(DESIGNS)} designs.')


if __name__ == '__main__':
    main()
